version: '3'
services:
  refbox_client:
    image: minhnh91/cfh_client
    network_mode: "host"
    volumes:
     - ./robot_example_ros.launch:/root/catkin_ws/src/atwork_refbox_ros_client/ros/launch/robot_example_ros.launch
     - ./config.yaml:/root/catkin_ws/src/atwork_refbox_comm/atwork_refbox/cfg/config.yaml
