version: '3'
services:
  refbox_client:
    image: minhnh91/mdr_erl_scenarios:latest
    network_mode: "host"
    volumes:
     - ./robot_example_ros.launch:/root/catkin_ws/src/atwork_refbox_ros_client/ros/launch/robot_example_ros.launch
